    SETLOCAL
    ECHO ON

    SET p1=%1%
    SET ASLGEN_KEYFIELD=%3
    SET ASLGEN_PARENTREF=%4

    SET GEN=C:\__Q1\KGRS042\Main\_Library\ASLGEN_CodeGEN

    SET OPTION=%2%
    IF NOT DEFINED OPTION GOTO EXIT
    IF %OPTION%==REGEN GOTO DO_REGEN
    IF %OPTION%==regen GOTO DO_REGEN
    IF %OPTION%==NEW GOTO DO_NEWDAL
    IF %OPTION%==new GOTO DO_NEWDAL
    ECHO *** INVALID SECOND PARAMETER. ONLY "NEW" OR "REGEN" ALLOWED
    GOTO EXIT

:DO_NEWDAL
    REM %GEN% NEW FSA %p1% _TableClass
    %GEN% NEW SD %p1% _DalObject
    GOTO DO_REST

:DO_REGEN
    REM %GEN% NEW FSA %p1% _TableClass
    %GEN% REGEN SD %p1% FSA_Da%p1%.cs
    GOTO DO_REST

:DO_REST
    ENDLOCAL

:EXIT

